name: Publish distribution to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish distribution to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/amazon-braket-algorithm-library
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install wheel
        run: python -m pip install --user --upgrade wheel
      - name: Install twine
        run: python -m pip install --user --upgrade twine
      - name: Install setuptools
        run: python -m pip install --user --upgrade setuptools
      - name: Build a binary wheel and a source tarball
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
